# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['MyClass']

# %% ../00_core.ipynb 3
class MyClass:
    """Nothing class"""
    def method():
        """Nothing method"""
        pass
